version: 2.1
orbs:
  node: circleci/node@4.0.0
  codecov: codecov/codecov@1.1.1

jobs:
  tests:
    docker:
      - image: circleci/node:14.15-browsers
    steps:
      - checkout
      - node/install-yarn
      - run:
          name: Show Node version
          command: |
            node --version
            yarn --version
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Run unit tests with coverage
          command: yarn cover
      - codecov/upload:
          file: coverage/*.json
  versioning:
    docker:
      - image: circleci/node:14.15
    steps:
      - checkout
      - run:
          name: Check package version
          command: yarn check-my-package-version -o megatroom -p nardini-academy -b master

workflows:
  ci:
    jobs:
      - tests
      - versioning:
          filters:
            branches:
              ignore: master
            tags:
              ignore: /.*/
