version: 2.1
orbs:
  node: circleci/node@5.0.2
  codecov: codecov/codecov@1.1.1

jobs:
  tests:
    docker:
      - image: cimg/node:16.13.0-browsers
    steps:
      - checkout
      - node/install-yarn
      - run:
          name: Show Node version
          command: |
            node --version
            yarn --version
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Run unit tests with coverage
          command: yarn cover
      - codecov/upload:
          file: coverage/*.json
  versioning:
    docker:
      - image: circleci/node:16.13.1-bullseye-browsers-legacy
    steps:
      - checkout
      - run:
          name: Check package version
          command: npx check-my-package-version -o megatroom -p nardini-academy -b master

workflows:
  ci:
    jobs:
      - tests
      - versioning:
          filters:
            branches:
              ignore: master
            tags:
              ignore: /.*/
